---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.0

inputs:
  - name: dp-sitemap

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-sitemap/ci/scripts/build.sh
