// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-sitemap/clients"
	"sync"
)

// Ensure, that ZebedeeClientMock does implement clients.ZebedeeClient.
// If this is not the case, regenerate this file with moq.
var _ clients.ZebedeeClient = &ZebedeeClientMock{}

// ZebedeeClientMock is a mock implementation of clients.ZebedeeClient.
//
// 	func TestSomethingThatUsesZebedeeClient(t *testing.T) {
//
// 		// make and configure a mocked clients.ZebedeeClient
// 		mockedZebedeeClient := &ZebedeeClientMock{
// 			CheckerFunc: func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
// 				panic("mock out the Checker method")
// 			},
// 			GetFileSizeFunc: func(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
// 				panic("mock out the GetFileSize method")
// 			},
// 		}
//
// 		// use mockedZebedeeClient in code that requires clients.ZebedeeClient
// 		// and then make assertions.
//
// 	}
type ZebedeeClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error

	// GetFileSizeFunc mocks the GetFileSize method.
	GetFileSizeFunc func(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CheckState is the checkState argument value.
			CheckState *healthcheck.CheckState
		}
		// GetFileSize holds details about calls to the GetFileSize method.
		GetFileSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAccessToken is the userAccessToken argument value.
			UserAccessToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
	}
	lockChecker     sync.RWMutex
	lockGetFileSize sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *ZebedeeClientMock) Checker(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ZebedeeClientMock.CheckerFunc: method is nil but ZebedeeClient.Checker was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}{
		ContextMoqParam: contextMoqParam,
		CheckState:      checkState,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(contextMoqParam, checkState)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedZebedeeClient.CheckerCalls())
func (mock *ZebedeeClientMock) CheckerCalls() []struct {
	ContextMoqParam context.Context
	CheckState      *healthcheck.CheckState
} {
	var calls []struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetFileSize calls GetFileSizeFunc.
func (mock *ZebedeeClientMock) GetFileSize(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
	if mock.GetFileSizeFunc == nil {
		panic("ZebedeeClientMock.GetFileSizeFunc: method is nil but ZebedeeClient.GetFileSize was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		URI             string
	}{
		Ctx:             ctx,
		UserAccessToken: userAccessToken,
		CollectionID:    collectionID,
		Lang:            lang,
		URI:             uri,
	}
	mock.lockGetFileSize.Lock()
	mock.calls.GetFileSize = append(mock.calls.GetFileSize, callInfo)
	mock.lockGetFileSize.Unlock()
	return mock.GetFileSizeFunc(ctx, userAccessToken, collectionID, lang, uri)
}

// GetFileSizeCalls gets all the calls that were made to GetFileSize.
// Check the length with:
//     len(mockedZebedeeClient.GetFileSizeCalls())
func (mock *ZebedeeClientMock) GetFileSizeCalls() []struct {
	Ctx             context.Context
	UserAccessToken string
	CollectionID    string
	Lang            string
	URI             string
} {
	var calls []struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		URI             string
	}
	mock.lockGetFileSize.RLock()
	calls = mock.calls.GetFileSize
	mock.lockGetFileSize.RUnlock()
	return calls
}
